version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - run: sudo apt-get update && sudo apt-get install wmctrl fluxbox x11-apps
      - run: sudo /usr/bin/killall Xvfb
      - run: sudo /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 4000x1800x24
      - run: fluxbox > /dev/null
             background: true
      - run: ./screenshotExample.sh
      - checkout
      - run: sudo apt-get install fluxbox
      - run: sudo systemctl restart lightdm.service

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

